/mv_camera:
  ros__parameters:
    camera_name: mv_camera

    analog_gain: 50
    exposure_time: 8000
    flip_image: true
    gamma: 60

    rgb_gain:
      b: 110
      g: 95
      r: 120

    saturation: 100

/armor_detector:
  ros__parameters:
    use_depth: false
    subscribe_compressed: false

    min_lightness: 170

    light:
      max_angle: 40.0
      max_ratio: 0.3
      min_ratio: 0.1

    armor:
      max_angle: 35.0
      max_center_ratio: 1.6
      min_center_ratio: 0.4
      min_light_ratio: 0.6
      max_large_center_distance: 5.0
      min_large_center_distance: 3.2
      max_small_center_distance: 3.1
      min_small_center_distance: 0.8

    number_classifier:
      height_factor: 2.0
      large_width_factor: 0.4
      small_width_factor: 0.56
      similarity_threshold: 0.5
/armor_processor:
  ros__parameters:
    tracker:
      max_match_distance: 0.2
      tracking_threshold: 5
      lost_threshold: 5
