/mv_camera:
  ros__parameters:
    camera_name: mv_camera

    analog_gain: 50
    exposure_time: 8000
    gamma: 100

    rgb_gain:
      b: 110
      g: 95
      r: 120

    saturation: 100

/armor_detector:
  ros__parameters:
    use_depth: false
    subscribe_compressed: false

    detect_color: 0

    min_lightness: 110

    light:
      max_angle: 40.0
      max_ratio: 0.42
      min_ratio: 0.1

    armor:
      max_angle: 35.0
      max_center_ratio: 1.6
      min_center_ratio: 0.4
      min_light_ratio: 0.6
      max_large_center_distance: 5.0
      min_large_center_distance: 3.2
      max_small_center_distance: 3.2
      min_small_center_distance: 0.8

    number_classifier:
      threshold: 0.9

/armor_processor:
  ros__parameters:
    tracker:
      max_match_distance: 0.2
      tracking_threshold: 5
      lost_threshold: 5
